# Generated by Django 4.2.3 on 2023-07-28 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='code',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
